# Setup
title:               Merter GÃ¼lbahar
tagline:             "Bilgisayar MÃ¼hendisi"
description:         "ğŸ’» KiÅŸisel Web BloÄŸu!"
url:                 https://merterr.com
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Merter GÃ¼lbahar
  linkedin:          https://www.linkedin.com/in/merter-g%C3%BClbahar-537723107/
  email:             mertergulbahar [at] gmail.com

#github contact
github:
  repo:              https://github.com/merterr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-170289912-1
